=== walter-rothlin/Source-Code/XML/distributionDesc.dtd
<?xml version="1.0" encoding="UTF-8"?><!ELEMENT PrinterName         (#PCDATA)><!ELEMENT Destination         (#PCDATA)><!ELEMENT Command             (#PCDATA)><!ELEMENT Renameing           (#PCDATA)><!ELEMENT Name                (#PCDATA)><!ELEMENT FirstName           (#PCDATA)><!ELEMENT Address             (#PCDATA)><!ELEMENT Subject             (#PCDATA)><!ELEMENT Text                (#PCDATA)><!-- open declaration   <!ELEMENT Text                ANY>--><!-- Example from a mixed content; No other possibility to define it; PCDATA has to be first element--><!ELEMENT Comment		 (#PCDATA | bold | italic | underline)*><!ELEMENT bold      		   (#PCDATA)><!ELEMENT italic      		 (#PCDATA)><!ELEMENT underline 		   (#PCDATA)><!ENTITY % convertionList "PDF | PS | ASC"><!ATTLIST Destination	protokol (ftp)       #REQUIRED	node CDATA           #REQUIRED	user CDATA           #REQUIRED	password CDATA       #REQUIRED	convertion CDATA     #REQUIRED	destinationDir CDATA #REQUIRED><!ATTLIST PrinterName convertion (%convertionList;) #REQUIRED><!ATTLIST TransferDestination                                        protokol            (ftp) #REQUIRED                                       node                CDATA #REQUIRED                                      user                CDATA #REQUIRED                                      password            CDATA #REQUIRED                                      convertion          CDATA #REQUIRED                                      destinationDir      CDATA #REQUIRED><!ATTLIST Receiver      type (asExcelAttachment |                              asPdfAttachment   |                              asAsciiAttachment |                              asAscii)            #REQUIRED><!ELEMENT FileTransfer (TransferDestination+)><!ELEMENT TransferDestination (PreAction?,Renameing?,PostAction?)><!--    CardinalitÃ¤t: 	? => 0,1						* => 0..n						+ => 1..n--><!ELEMENT PreAction (Command+)><!ELEMENT PostAction (Command+)><!ELEMENT Printing (PrinterName+)><!ELEMENT Email       (Receiver+)><!ELEMENT Receiver (FullName,Address,Subject,Text)><!ELEMENT FullName ((Name,FirstName,MiddleName) | (FirstName,MiddleName,Name) ) ><!ELEMENT MiddleName EMPTY>  <!-- definition of an empty tag.  ANY declaration of beliebigen Inhalt--><!ELEMENT DestinationDescription (FileTransfer?,Printing?,Email?,Comment)>

=== walter-rothlin/Source-Code/XML/distributionDesc.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?> <!-- 	UTF-8 and no are default; order is defined and can't be changed	standalone=no means that other files are used within this document (other value is yes)		<?xml ... is not required		if there is a <?xml .... no commend is allowed before --><?xml-stylesheet type="text/css" href="distributionDesc.css" ?><!-- <? is a Verarbeitungsanweisung; nicht innerhalb von TAGS erlaubt <? is optional; if it is there - No commend line allowed before this line--><!DOCTYPE DestinationDescription SYSTEM "Y:\Data\SourceCode\XML\distributionDesc.dtd" [	<!ELEMENT birth_date (#PCDATA)>]><!--	Attribute SYSTEM is an URL or a filename--><!--  Internal DTD:			<!DOCTYPE DestinationDescription [			]>--><!--    Well formed:		One root element		Emty tags using <tag/>		Case sensitive		A-Z, a-z, 0-9, äöü... , [ _-.: (: reserved for name spaces)]    Constraint: (0-9, - . nicht am Anfang)		keine spaces; kein XML sunstring; : reserved for name spaces		<   => &lt;      & => &amp; (darf nicht im Inhalt eines Elementes verwendet werden)		>  => &gt;       " => &quot;     ' => &apos;		double - ist not allowed within a commend		Reihenfolge Attribute not relevant		Attribute values between ' or " but not mixed--><DestinationDescription>	<!-- Test commend -->	<FileTransfer>		<TransferDestination protokol="ftp" user="a43" password="1234" node="122.64.55.200" convertion="PDF" destinationDir="/app/data/reports">			<PreAction>				<Command>filterData($subType)</Command>				<Command>removeHeaderLine(2)</Command>				<Command>createDestinationDir($date)</Command>			</PreAction>			<Renameing>				 $filename --> ${filename}.inProgress --> ${filename}.done			</Renameing>			<PostAction>				<Command>updateLog($filename)</Command>			</PostAction>		</TransferDestination>	</FileTransfer>	<Printing>		<PrinterName convertion="PDF">zrhpr1.tszrh.ska.com</PrinterName>		<!-- XPath: DestinationDescription/Printing/PrinterName[1]/@convertion  = ASC -->		<PrinterName convertion="ASC">sithits4.csfb.com</PrinterName>		<PrinterName convertion="PS">zhpr</PrinterName>	</Printing>	<Email>		<Receiver type="asExcelAttachment">			<FullName>				<FirstName>Walter</FirstName>				<MiddleName/>				<Name>Rothlin</Name>			</FullName>			<Address>Walter@Rothlin.com</Address>			<Subject>Report $name $date</Subject>			<Text><![CDATA[			Attached you find <b>${name}</b> report			     ]]></Text>		</Receiver>	</Email>	<Comment>		<!-- Example from a mixed content -->		Dies ist eine <underline>Beschreibung</underline> von <italic> einer DestinationDescription</italic>	</Comment></DestinationDescription>
