=== walter-rothlin/Source-Code/XML/leute.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2006 sp2 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="vorname"  type="xs:string"/>
	<xs:element name="mittelinitial"  type="xs:string"/>
	<xs:element name="nachname"  type="xs:string"/>
	<xs:element name="beruf" type="xs:string"/>	
	<xs:element name="hobby"  type="xs:string"/>

	<xs:element name="leute">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="person" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="name">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="vorname"/>
				<xs:element ref="mittelinitial" minOccurs="0"/>
				<xs:element ref="nachname"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="person">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="beruf"  minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="hobby" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="geboren" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:short">
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="gestorben" type="xs:short"/>
		</xs:complexType>
	</xs:element>

	

</xs:schema>

=== walter-rothlin/Source-Code/XML/leute.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="application/xml" url=" leute.xsl"?>
<leute xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Y:\Data\SourceCode\XML\leute.xsd">

	<!-- 1.Person -->
	<person geboren="1912" gestorben="1954">
		<name>
			<vorname>Alan</vorname>
			<nachname>Turing</nachname>
		</name>
		<beruf>Informatiker</beruf>
		<beruf>Mathematiker</beruf>
		<beruf>Kryptograph</beruf>
	</person>
	
	<!-- 2.Person -->
	<person geboren="1918" gestorben="1988">
		<name>
		    <!--- Kommentar -->
			<vorname>Richard</vorname>
			<mittelinitial>P</mittelinitial>
			<nachname>Feynman</nachname>
		</name>
		<beruf>Physiker</beruf>
		<hobby>Spielt Bongos</hobby>
	</person>
	
	<!-- 3.Person -->
	<person geboren="1960">
		<name>
			<vorname>Walter</vorname>
			<mittelinitial>M</mittelinitial>
			<nachname>Rothlin</nachname>
		</name>
		<beruf>El. Ing HTL / FH</beruf>
		<hobby>Sport</hobby>
	</person>
</leute>
