=== walter-rothlin/Source-Code/XML/people.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
                    targetNamespace="http://www.rothlin.com" 
                    elementFormDefault="qualified" 
                    attributeFormDefault="qualified">
	<xs:element name="people">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="person" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="pet" type="xs:string"/>
							<xs:element name="phone" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="location" use="required">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="home"/>
														<xs:enumeration value="mobile"/>
														<xs:enumeration value="office"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== walter-rothlin/Source-Code/XML/people.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><rot:people xmlns:rot="http://www.rothlin.com"       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"       xsi:schemaLocation="http://www.rothlin.com people.xsd">       	<rot:person>		<rot:name>Jane Doe</rot:name>		<rot:pet>Fluffy</rot:pet>		<rot:phone rot:location="home">01 460 14 40</rot:phone>		<rot:phone rot:location="mobile">079 702 95 93</rot:phone>		<rot:phone rot:location="office">079 702 95 93</rot:phone>	</rot:person>		<rot:person>		<rot:name>Walti Rothlin</rot:name>		<rot:pet>Browny</rot:pet>	<rot:phone rot:location="mobile">01 460 14 41</rot:phone>	</rot:person>		<rot:person>		<rot:name>Walti Bernhard</rot:name>		<rot:pet>Lassy</rot:pet>		<rot:phone rot:location="home">01 460 14 42</rot:phone>	</rot:person></rot:people>
